# ./docker-compose/docker-compose.yml
version: '3'
services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: gajo
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
  frontend:
    restart: always 
    image: "gtertrais/front:dev"
  backend:
    depends_on:
      - mysql_db
    restart: always 
    image: "gtertrais/server:dev"
    environment:
      MYSQL_DATABASE: gajo
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_HOST_IP: mysql_db
  proxy:
    restart: always 
    image: "gtertrais/proxy:dev"
    ports:
      - "80:80"
      - "443:443"