# ./docker-compose/docker-compose.yml
version: '3'
services:
  frontend:
    image: "gtertrais/front:latest"
    networks:
      - sub-etha
  backend:
    image: "gtertrais/server:latest"
    networks:
      - sub-etha
  proxy:
    image: "gtertrais/proxy:latest"
    networks:
      - sub-etha
    ports:
      - "80:80"
networks:
  sub-etha: