# ./docker-compose/docker-compose.yml
version: '3'
services:
  frontend:
    restart: always 
    image: "gtertrais/front:dev"
  backend:
    restart: always 
    image: "gtertrais/server:dev"
  proxy:
    restart: always 
    image: "gtertrais/proxy:dev"
    ports:
      - "80:80"
      - "443:443"