# ./docker-compose/docker-compose.yml
version: '3'
services:
  frontend:
    restart: always 
    image: "gtertrais/front:pre"
  backend:
    restart: always 
    image: "gtertrais/server:pre"
  admin:
    restart: always 
    image: "gtertrais/admin:pre"
  proxy:
    restart: always 
    image: "gtertrais/proxy:pre"
    ports:
      - "80:80"
      - "443:443"