# ./docker-compose/docker-compose.yml
version: '3'
services:
  frontend:
    build: ../front
    image: "front"
    networks:
      - sub-etha
  backend:
    build: ../server
    image: "server"
    networks:
      - sub-etha
  proxy:
    build: ../proxy
    image: "proxy"
    networks:
      - sub-etha
    ports:
      - "80:80"
networks:
  sub-etha: