# ./docker-compose/docker-compose.yml
version: '3'
services:
  frontend:
    restart: always 
    image: "gtertrais/front:latest"
  backend:
    restart: always 
    image: "gtertrais/server:latest"
  proxy:
    restart: always 
    image: "gtertrais/proxy:latest"
    ports:
      - "80:80"
      - "443:443"