# ./docker-compose/docker-compose.yml
version: '3'

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      MYSQL_DATABASE: gajo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
    networks:
      - sub-etha
  frontend:
    restart: always 
    image: "gtertrais/front:latest"
    networks:
      - sub-etha
  backend:
    restart: always 
    image: "gtertrais/server:latest"
    networks:
      - sub-etha
    environment:
      MYSQL_DATABASE: gajo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST_IP: mysql_db
  proxy:
    restart: always 
    image: "gtertrais/proxy:latest"
    networks:
      - sub-etha
    ports:
      - "80:80"
      - "443:443"
  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    networks:
     - sub-etha
networks:
  sub-etha: