# ./docker-compose/docker-compose.yml
version: '3'
services:
  frontend:
    restart: always 
    image: "gtertrais/front"
  backend:
    restart: always 
    image: "gtertrais/server"
  admin:
    restart: always 
    image: "gtertrais/admin"
  proxy:
    restart: always 
    image: "gtertrais/proxy"
    ports:
      - "80:80"
      - "443:443"